### ISSUE TITLE
Information about Splunk detection

### ISSUE THREAD

**Issue by syrius01** [TBGSecurity/splunk_shells#1]
Hi,

Not sure if you could help me on this situation; I am trying to make a script that detects if Apache Splunk requires auth or not but I'm having a hard time since every time I get HTTP code 303, here's the PHP script so far;

https://pastebin.com/1JmH6rTU

Any help/suggestions would be very appreciated,

Thanks

**Comment by MrJester** [comment]
I mean that would have to be a release prior to 5 I think that was when they implemented authentication to be the default on all Splunk installs. Not sure it would be a fruitful task of looking for this. I guess it also couldn't hurt. When you get the 303 where is it redirecting you to? What version of Splunk are you testing this on?
